In [2]:
%pip install opencv-python

In [3]:
%pip install cmake

Note: you may need to restart the kernel to use updated packages.


In [4]:
%pip install face_recognition

Note: you may need to restart the kernel to use updated packages.


In [5]:
%pip install dlib

Note: you may need to restart the kernel to use updated packages.


In [1]:
import pandas as pd
import numpy as np
import cv2
import face_recognition
import pathlib
from tkinter import Tk
from tkinter.filedialog import askopenfilename
import os

In [2]:
cascade_path = pathlib.Path(cv2.__file__).parent.absolute() / "data/haarcascade_frontalface_default.xml"

In [3]:
print(cascade_path)

C:\Users\Tim\AppData\Local\Programs\Python\Python311\Lib\site-packages\cv2\data\haarcascade_frontalface_default.xml


In [4]:
clf = cv2.CascadeClassifier(str(cascade_path))
camera = cv2.VideoCapture("Videos/Громкий_вопрос_с_Гавриилом_Гордеевым.mp4")

In [5]:
#image_of_mat = face_recognition.load_image_file("Images/Mat 1.png")
#image_of_mat_encoding = face_recognition.face_encodings(image_of_mat)
camera = cv2.VideoCapture("Videos/Громкий_вопрос_с_Гавриилом_Гордеевым.mp4")
def encode_faces(folder):
    list_filename = []
    list_people_encoding = []
    
    for filename in os.listdir(folder):
        known_image = face_recognition.load_image_file(f'{folder}{filename}')
        known_encoding = face_recognition.face_encodings(known_image)[0]
        list_filename.append(filename)
        list_people_encoding.append(known_encoding)
    return list_filename, list_people_encoding


def find_target_face(list_filenames, encoded_faces, image):
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    face_locations = face_recognition.face_locations(gray)
    face_encodings = face_recognition.face_encodings(gray, face_locations)


    for (top, right, bottom, left), face_encoding in zip(face_locations, face_encodings):
        matches = face_recognition.compare_faces(encoded_faces, face_encoding, tolerance=0.55)
        
        name = "Guest"
        if True in matches:
            first_match_index = matches.index(True)
            name = list_filenames[first_match_index].split(' ')[0]
        create_frame((top, right, bottom, left), name, image)


def create_frame(location, label, image):
    top, right, bottom, left = location

    cv2.rectangle(image, (left, top), (right, bottom), (255, 0, 0), 2)
    
    cv2.rectangle(image, (left, bottom + 20), (right, bottom), (255, 0, 0), cv2.FILLED)
    cv2.putText(image, label, (left + 10, bottom + 14), cv2.FONT_HERSHEY_DUPLEX, 0.4, (255,255,255), 1)



def render_image(image):
    rgb_img = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    cv2.imshow('Face Recognition', rgb_img)
    cv2.waitKey(0)



list_filenames, encoded_faces = encode_faces('Images/')
known_faces_names = ["Mat", "Pop", "Poz", "Shast"]
while True:
    _, frame = camera.read()
    find_target_face(list_filenames, encoded_faces, frame)
    #gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    #faces = clf.detectMultiScale(gray, scaleFactor=1.15, minNeighbors=5, minSize=(20, 20), flags=cv2.CASCADE_SCALE_IMAGE)
    
    #for(x, y, width, height) in faces:
    #    cv2.rectangle(frame, (x,y), (x+width, y+height), (255, 255, 0), 2)
    cv2.imshow("Faces", frame)
    if cv2.waitKey(1) == ord("q"):
        break
camera.release()
cv2.destroyAllWindows()





TypeError: compute_face_descriptor(): incompatible function arguments. The following argument types are supported:
    1. (self: _dlib_pybind11.face_recognition_model_v1, img: numpy.ndarray[(rows,cols,3),numpy.uint8], face: _dlib_pybind11.full_object_detection, num_jitters: int = 0, padding: float = 0.25) -> _dlib_pybind11.vector
    2. (self: _dlib_pybind11.face_recognition_model_v1, img: numpy.ndarray[(rows,cols,3),numpy.uint8], num_jitters: int = 0) -> _dlib_pybind11.vector
    3. (self: _dlib_pybind11.face_recognition_model_v1, img: numpy.ndarray[(rows,cols,3),numpy.uint8], faces: _dlib_pybind11.full_object_detections, num_jitters: int = 0, padding: float = 0.25) -> _dlib_pybind11.vectors
    4. (self: _dlib_pybind11.face_recognition_model_v1, batch_img: List[numpy.ndarray[(rows,cols,3),numpy.uint8]], batch_faces: List[_dlib_pybind11.full_object_detections], num_jitters: int = 0, padding: float = 0.25) -> _dlib_pybind11.vectorss
    5. (self: _dlib_pybind11.face_recognition_model_v1, batch_img: List[numpy.ndarray[(rows,cols,3),numpy.uint8]], num_jitters: int = 0) -> _dlib_pybind11.vectors

Invoked with: <_dlib_pybind11.face_recognition_model_v1 object at 0x0000020DAE7A7AB0>, array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8), <_dlib_pybind11.full_object_detection object at 0x0000020DAEC9BA30>, 1

In [6]:
while True:
    _, frame = camera.read()
    frame
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    faces = clf.detectMultiScale(
        gray,
        scaleFactor=1.15,
        minNeighbors=5,
        minSize=(20, 20),
        flags=cv2.CASCADE_SCALE_IMAGE
    )
    print(faces)
    for(x, y, width, height) in faces:
        cv2.rectangle(frame, (x,y), (x+width, y+height), (255, 255, 0), 2)
    cv2.imshow("Faces", frame)
    if cv2.waitKey(1) == ord("q"):
        break
camera.release()
cv2.destroyAllWindows()

()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
[[278 127 129 129]]
[[277 126 130 130]]
[[278 127 126 126]]
[[275 126 128 128]]
[[276 127 125 125]]
[[276 127 123 123]]
[[273 127 124 124]]
[[271 124 126 126]]
[[269 123 126 126]]
[[268 123 126 126]]
[[267 120 127 127]]
[[267 121 125 125]]
[[267 121 124 124]]
[[264 119 126 126]]
[[262 118 128 128]]
[[260 115 130 130]]
[[258 114 132 132]]
[[257 112 133 133]]
[[259 114 130 130]]
[[257 113 130 130]]
[[260 115 126 126]]
[[259 113 127 127]]
[[257 109 131 131]]
[[263 110 126 126]]
[[264 106 130 130]]
[[273 103 129 129]]
[[271  99 128 128]]
[[279  99 125 125]]
[[279  98 123 123]]
[[279  97 123 123]]
()
[[285  98 123 123]]
[[284  99 120 120]]
()
()
[[281  96 121 121]]
[[286  98 117 117]]
[[287  98 116 116]]
[[279  96 121 121]]
[[276  95 120 120]]
()
[[277  95 118 118]]
[[276  94 126 126]]
[[278  95 124 124]]
[[280  96 123 123]]
[[275  92 126 126]]
[[275  93 126 126]]
[[278  96 123 123]]
[[277  96 123 123]]
[[278  

In [ ]:
### CODE SAVE

image_of_mat = face_recognition.load_image_file("Images/Mat 1.png")
image_of_mat_encoding = face_recognition.face_encodings(image_of_mat)

def encode_faces(folder):
    list_people_encoding = []

    for filename in os.listdir(folder):
        known_image = face_recognition.load_image_file(f'{folder}{filename}')
        known_encoding = face_recognition.face_encodings(known_image)[0]

        list_people_encoding.append((known_encoding, filename))
    return list_people_encoding


def find_target_face():
    face_location = face_recognition.face_locations(image_of_mat)

    for person in encode_faces('Images/'):
        encoded_face = person[0]
        filename = person[1]

        is_target_face = face_recognition.compare_faces(encoded_face, image_of_mat_encoding, tolerance=0.55)
        print(f'{is_target_face}{filename}')

        if face_location:
            face_number = 0
            for location in face_location:
                if is_target_face[face_number]:
                    label = filename.split()
                    create_frame(location, label[0])

                face_number += 1



def create_frame(location, label):
    top, right, bottom, left = location

    cv2.rectangle(image_of_mat, (left, top), (right, bottom), (255, 0, 0), 2)
    
    cv2.rectangle(image_of_mat, (left, bottom + 20), (right, bottom), (255, 0, 0), cv2.FILLED)
    cv2.putText(image_of_mat, label, (left + 3, bottom + 14), cv2.FONT_HERSHEY_DUPLEX, 0.4, (255,255,255), 1)



def render_image():
    rgb_img = cv2.cvtColor(image_of_mat, cv2.COLOR_BGR2RGB)
    cv2.imshow('Face Recognition', rgb_img)
    cv2.waitKey(0)


In [5]:
print(faces)

NameError: name 'faces' is not defined